
class DataModel {
	_instance = null;
	static instance() { return (this._instance == null ? this._instance = new DataModel() : this._instance) };

	static modelRemoteGetModelUrl = 'https://2y3ndtoxei.execute-api.us-west-1.amazonaws.com/default/patiModelContent';
	static modelRemoteVersionCheckUrl = 'https://2y3ndtoxei.execute-api.us-west-1.amazonaws.com/default/patiModelVersion';
	static modelRemoteUpdateInterval = 55000;

	static happeningNowUpdateInterval = 30000;

	static festivalName = "Pati Festival"


	static modelVersion = 1000;
	static dataArtists = {
		'Alafia Ire': { fullName: `Alafia Con Ire`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `05_Alafia_Con_Ire.png` },
		'Alexander Carbo': { fullName: `Alexander Carbó`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `08_Alexander_Carbo.png` },
		'Alexandra Toledo': { fullName: `Alexandra Toledo`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `13_Alexandra_Toledo.png` },
		'Angela Jauregui': { fullName: `Angela de la Caridad Jauregui`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `10_Angela_de_la_Caridad_Jauregui.png` },
		'DJ Goodfoot': { fullName: `DJ Goodfoot`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `03_DJ_Goodfoot.png` },
		'DJ Paulazo': { fullName: `DJ Paulazo`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `02_DJ_Paulazo.png` },
		'DJ Yala': { fullName: `DJ Yala`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `01_DJ_Yala.png` },
		'DJ Puma': { fullName: `El Puma DJ`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `04_El_Puma_DJ.png` },
		'Helen': { fullName: `Helen`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `06_Helen.png` },
		'Ido Flaishon': { fullName: `Ido Flaishon`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `18_Ido_Flaishon.png` },
		'Jonas Reichert': { fullName: `Jonas Reichert`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `21_Jonas_Reichert.png` },
		'Kimberly Wirt': { fullName: `Kimberly Wirt`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `14_Kimberly_Wirt.png` },
		'Leonardo Moya': { fullName: `Leonardo Martinez Moya`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `20_Leonardo_Martinez_Moya.png` },
		'Lucas Flemming': { fullName: `Lucas Flemming`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `17_Lucas_Flemming.png` },
		'Lynet Rubio': { fullName: `Lynet Rivero Rubio`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `09_Lynet_Rivero_Rubio.png` },
		'Ruggiero Palombella': { fullName: `Ruggiero Palombella`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `12_Ruggiero_Palombella.png` },
		'Sassan Alivaliollahi': { fullName: `Sassan Alivaliollahi`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `19_Sassan_Alivaliollahi.png` },
		'Silvio Perez': { fullName: `Silvio Leroy Pérez`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `11_Silvio_Leroy_Perez.png` },
		'Tanja': { fullName: `Tanja`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `07_Tanja.png` },
		'Timo Lingnau': { fullName: `Timo Lingnau`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `16_Timo_Lingnau.png` },
		'Wendy Solanch': { fullName: `Wendy Solanch`, insta: ``, bio: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus nisl tincidunt eget nullam non nisi. Dignissim enim sit amet venenatis urna cursus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ut sem nulla pharetra diam sit amet. Leo integer malesuada nunc vel risus commodo viverra. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Volutpat diam ut venenatis tellus. Etiam non quam lacus suspendisse. Diam quis enim lobortis scelerisque. Et malesuada fames ac turpis egestas. Egestas congue quisque egestas diam in arcu cursus euismod. Ultricies lacus sed turpis tincidunt id aliquet risus.\n\nVel fringilla est ullamcorper eget nulla facilisi etiam. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.`, facebook: ``, portrait: `15_Wendy_Solanch.png` },
	};

	static dataScheduleRaw =
		[
			{ id: 1201, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alex Toledo', sessionMainTitle: 'Choreography & Interpretation', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Room 01`, level: `1`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexandra Toledo', artistTwo: '', flag: false },
			{ id: 1202, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Afro-Conte﻿mporary', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Room 02`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 1203, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lynet', sessionMainTitle: 'Técnica Yoruba', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Room 03`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lynet Rubio', artistTwo: '', flag: true },
			{ id: 1204, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Rumba Guaguanco', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Room 04`, level: `2`, partnerWork: `1`, levelSpecial: `1`, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: true },
			{ id: 1205, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Técnica', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Room 05`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 1301, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'Timba Roger Style', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Room 01`, level: `2`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: false },
			{ id: 1302, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Lynet', sessionMainTitle: 'Rumba Yambu', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Room 02`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Lynet Rubio', flag: true },
			{ id: 1303, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido', sessionMainTitle: 'Pacha﻿nga', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Room 03`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: '', flag: true },
			{ id: 1304, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Arar﻿á', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Room 04`, level: `1`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },
			{ id: 1305, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Helen & Tanja', sessionMainTitle: 'Rueda Active Following', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Room 05`, level: `0`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Helen ', artistTwo: 'Tanja ', flag: true },

			{ id: 1103, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Lunch Break', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '13:15 - 14:15', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T13:15', endTime: '2024-06-14T14:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

			{ id: 1401, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo & Kimmy', sessionMainTitle: 'Casino Partnerwork Musicality ', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Room 01`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Kimberly Wirt', flag: false },
			{ id: 1402, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Angela', sessionMainTitle: 'Ladystyling', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Room 02`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Angela Jauregui', artistTwo: '', flag: true },
			{ id: 1403, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'Cuban Movement Practice', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Room 03`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
			{ id: 1404, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Rumba Columbia', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Room 04`, level: `2`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 1405, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lucas', sessionMainTitle: 'Rueda Transiciones ', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Room 05`, level: `1`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lucas Flemming', artistTwo: '', flag: true },

			{ id: 1501, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lucas & Kimmy', sessionMainTitle: 'Casino Transiciones', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Room 01`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lucas Flemming', artistTwo: 'Kimberly Wirt', flag: false },
			{ id: 1502, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio', sessionMainTitle: 'Rumba Columbia', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Room 02`, level: `1`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: '', flag: true },
			{ id: 1503, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lynet', sessionMainTitle: 'Afro-Conte﻿mporary', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Room 03`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lynet Rubio', artistTwo: '', flag: true },
			{ id: 1504, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Lumbanche', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Room 04`, level: `1`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },
			{ id: 1505, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Advanced Caminando', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Room 05`, level: `2`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 1601, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Room 01`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
			{ id: 1602, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Wendy', sessionMainTitle: 'Reggaeton ', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Room 02`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Wendy Solanch', artistTwo: '', flag: true },
			{ id: 1603, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jonas (Tanzpause)', sessionMainTitle: 'An interactive Journey: Roots of Timba', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Room 03`, level: ``, partnerWork: ``, levelSpecial: `3`, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Jonas Reichert', artistTwo: '', flag: true },
			{ id: 1604, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Palo Genérico', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Room 04`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 1605, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Hidden Structurs', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Room 05`, level: `2`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 1700, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

			{ id: 2201, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Alex Toledo', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Room 01`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Alexandra Toledo', flag: false },
			{ id: 2202, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido', sessionMainTitle: 'CASI﻿NO NUDOS', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Room 02`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: '', flag: true },
			{ id: 2203, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Cha Cha Cha Partnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Room 03`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
			{ id: 2204, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'VODOO', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Room 04`, level: `2`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 2205, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Técnica', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Room 05`, level: `0`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 2301, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Timba PArtnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Room 01`, level: `2`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
			{ id: 2302, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'FOOTWORK LOCO', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Room 02`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
			{ id: 2303, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Bolero Partnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Room 03`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
			{ id: 2304, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'GÜiR﻿O', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Room 04`, level: `1`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 2305, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda UNusual Trans﻿icions', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Room 05`, level: `0`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 2103, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Lunch Break', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '13:15 - 14:15', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T13:15', endTime: '2024-06-14T14:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

			{ id: 2401, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido & Wendy', sessionMainTitle: 'CASINO PARTNERWORK ', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Room 01`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: 'Wendy Solanch', flag: false },
			{ id: 2402, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger & Kimmy', sessionMainTitle: 'CASINO CON RUMBA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Room 02`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: 'Kimberly Wirt', flag: true },
			{ id: 2403, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Danzón', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Room 03`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
			{ id: 2404, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Angela', sessionMainTitle: 'MAKUTA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Room 04`, level: `2`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Angela Jauregui', artistTwo: '', flag: true },
			{ id: 2405, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Helen & Tanja', sessionMainTitle: 'SON RUEDA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Room 05`, level: `1`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Helen ', artistTwo: 'Tanja ', flag: true },

			{ id: 2501, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Son Planchas &  Tornillos', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Room 01`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
			{ id: 2502, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo & Wendy', sessionMainTitle: 'CASINO NUDOS', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Room 02`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Wendy Solanch', flag: true },
			{ id: 2503, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jonas (Tanzpause)', sessionMainTitle: 'Structure of Timba', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Room 03`, level: `0`, partnerWork: ``, levelSpecial: `3`, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Jonas Reichert', artistTwo: '', flag: true },
			{ id: 2504, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Chachalokafun', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Room 04`, level: `1`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },

			{ id: 2601, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alex Toledo', sessionMainTitle: 'Ladystyling', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Room 01`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexandra Toledo', artistTwo: '', flag: false },
			{ id: 2602, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'MEN STYLE ', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Room 02`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
			{ id: 2603, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo & Lucas', sessionMainTitle: 'Timba Musicality', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Room 03`, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Lucas Flemming', flag: true },
			{ id: 2604, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'IYESA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Room 04`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
			{ id: 2605, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Llanta', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Room 05`, level: `2`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

			{ id: 2700, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

			// { id: 3001, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type2', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Registration Starts', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3002, group: [], groupTitle: 'Berlin Experience', groupSubtitle: '', itemType: 'type2', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Berlin Experience', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '13:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-19T13:00', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3003, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Berlin Highlights City Tour with Rueda de Casino', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '13:00 - 15:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-19T13:00', endTime: '2024-06-14T15:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3004, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: ``, sessionMainTitle: 'Afternoon Social', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:00 - 18:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-19T15:00', endTime: '2024-06-15T18:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3005, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Beginner Bootcamp', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '18:00 - 20:30', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-06-15T18:00', endTime: '2024-06-15T20:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3006, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Pre-Party Workshop', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '21:00 - 22:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-06-15T21:00', endTime: '2024-06-15T22:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
			// { id: 3007, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Welcome Party', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '22:00 - 03:00', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-06-15T22:00', endTime: '2024-06-15T03:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

			// { id: 3008, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

		]


	//this is formatted in LauncherController during initialize() based on dataRaw;
	static dataArtistsList = null;
	static dataScheduleListsByDay = null;
}

export default DataModel;