
class DataModel {
    _instance = null;
    static instance() { return (this._instance == null ? this._instance = new DataModel() : this._instance) };

    static modelRemoteGetModelUrl = 'https://2y3ndtoxei.execute-api.us-west-1.amazonaws.com/default/patiModelContent';
    static modelRemoteVersionCheckUrl = 'https://2y3ndtoxei.execute-api.us-west-1.amazonaws.com/default/patiModelVersion';
    static modelRemoteUpdateInterval = 55000;

    static happeningNowUpdateInterval = 30000;

    static festivalName = "Pati Festival"


    static modelVersion = 1000;
    static dataArtists = {
        'DJ Yala': { fullName: `DJ Yala`, insta: ``, bio: ``, facebook: ``, portrait: `01_DJ_Yala.png` },
        'DJ Paulazo': { fullName: `DJ Paulazo`, insta: ``, bio: ``, facebook: ``, portrait: `02_DJ_Paulazo.png` },
        'DJ Goodfoot': { fullName: `DJ Goodfoot`, insta: ``, bio: ``, facebook: ``, portrait: `03_DJ_Goodfoot.png` },
        'DJ Puma': { fullName: `El Puma DJ`, insta: ``, bio: ``, facebook: ``, portrait: `04_El_Puma_DJ.png` },
        'Alafia Ire': { fullName: `Alafia Con Ire`, insta: ``, bio: ``, facebook: ``, portrait: `05_Alafia_Con_Ire.png` },
        'Helen ': { fullName: `Helen`, insta: ``, bio: ``, facebook: ``, portrait: `06_Helen.png` },
        'Tanja ': { fullName: `Tanja`, insta: ``, bio: ``, facebook: ``, portrait: `07_Tanja.png` },
        'Alexander Carbo': { fullName: `Alexander Carbó`, insta: ``, bio: ``, facebook: ``, portrait: `08_Alexander_Carbo.png` },
        'Lynet Rubio': { fullName: `Lynet Rivero Rubio`, insta: ``, bio: ``, facebook: ``, portrait: `09_Lynet_Rivero_Rubio.png` },
        'Angela Jauregui': { fullName: `Angela de la Caridad Jauregui`, insta: ``, bio: ``, facebook: ``, portrait: `10_Angela_de_la_Caridad_Jauregui.png` },
        'Silvio Perez': { fullName: `Silvio Leroy Pérez`, insta: ``, bio: ``, facebook: ``, portrait: `11_Silvio_Leroy_Perez.png` },
        'Ruggiero Palombella': { fullName: `Ruggiero Palombella`, insta: ``, bio: ``, facebook: ``, portrait: `12_Ruggiero_Palombella.png` },
        'Alexandra Toledo': { fullName: `Alexandra Toledo`, insta: ``, bio: ``, facebook: ``, portrait: `13_Alexandra_Toledo.png` },
        'Kimberly Wirt': { fullName: `Kimberly Wirt`, insta: ``, bio: ``, facebook: ``, portrait: `14_Kimberly_Wirt.png` },
        'Wendy Solanch': { fullName: `Wendy Solanch`, insta: ``, bio: ``, facebook: ``, portrait: `15_Wendy_Solanch.png` },
        'Timo Lingnau': { fullName: `Timo Lingnau`, insta: ``, bio: ``, facebook: ``, portrait: `16_Timo_Lingnau.png` },
        'Lucas Flemming': { fullName: `Lucas Flemming`, insta: ``, bio: ``, facebook: ``, portrait: `17_Lucas_Flemming.png` },
        'Ido Flaishon': { fullName: `Ido Flaishon`, insta: ``, bio: ``, facebook: ``, portrait: `18_Ido_Flaishon.png` },
        'Sassan Alivaliollahi': { fullName: `Sassan Alivaliollahi`, insta: ``, bio: ``, facebook: ``, portrait: `19_Sassan_Alivaliollahi.png` },
        'Leonardo Moya': { fullName: `Leonardo Martinez Moya`, insta: ``, bio: ``, facebook: ``, portrait: `20_Leonardo_Martinez_Moya.png` },
        'Jonas Reichert': { fullName: `Jonas Reichert`, insta: ``, bio: ``, facebook: ``, portrait: `21_Jonas_Reichert.png` },

    };

    static dataScheduleRaw =
        [

            { id: 100, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type2', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Registration Starts', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00', room: ``, level: ``, startTime: '2024-07-19T11:00', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

            { id: 201, group: [201,202,203,204,205], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alex Toledo', sessionMainTitle: 'Choreography & Interpretation', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00 - 12:00', room: `Room 01`, level: `1`, startTime: '2024-07-19T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexandra Toledo', artistTwo: '', flag: false },
            { id: 202, group: [201,202,203,204,205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Afro-Contempary', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00 - 12:00', room: `Room 02`, level: `0`, startTime: '2024-07-19T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
            { id: 203, group: [201,202,203,204,205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lynet', sessionMainTitle: 'Técnica Yoruba', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00 - 12:00', room: `Room 03`, level: `0`, startTime: '2024-07-19T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lynet Rubio', artistTwo: '', flag: true },
            { id: 204, group: [201,202,203,204,205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio / Angela', sessionMainTitle: 'Rumba Guaguanco', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00 - 12:00', room: `Room 04`, level: `2`, startTime: '2024-07-19T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: true },
            { id: 205, group: [201,202,203,204,205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Técnica Yoruba', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '11:00 - 12:00', room: `Room 05`, level: `0`, startTime: '2024-07-19T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 301, group: [301,302,303,304,305], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'Timba Roger Style', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '12:15 - 13:15', room: `Room 01`, level: `2`, startTime: '2024-07-19T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: false },
            { id: 302, group: [301,302,303,304,305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio / Lynet', sessionMainTitle: 'Rumba Yambu', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '12:15 - 13:15', room: `Room 02`, level: `0`, startTime: '2024-07-19T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: 'Lynet Rubio', flag: true },
            { id: 303, group: [301,302,303,304,305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido', sessionMainTitle: 'Pachanga', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '12:15 - 13:15', room: `Room 03`, level: `0`, startTime: '2024-07-19T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: '', flag: true },
            { id: 304, group: [301,302,303,304,305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Arará', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '12:15 - 13:15', room: `Room 04`, level: `1`, startTime: '2024-07-19T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },
            { id: 305, group: [301,302,303,304,305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Hellen / Tanja', sessionMainTitle: 'Rueda Active Following', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '12:15 - 13:15', room: `Room 05`, level: `0`, startTime: '2024-07-19T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Helen ', artistTwo: 'Tanja ', flag: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 103, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Lunch Break', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '13:15 - 14:15', room: ``, level: ``, startTime: '2024-07-19T13:15', endTime: '2024-06-14T14:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 401, group: [401,402,403,404,405], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo / Kimmy', sessionMainTitle: 'Casino Partnerwork Musicality', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '14:15 - 15:15', room: `Room 01`, level: `1`, startTime: '2024-07-19T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Kimberly Wirt', flag: false },
            { id: 402, group: [401,402,403,404,405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Angela', sessionMainTitle: 'Ladystyling', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '14:15 - 15:15', room: `Room 02`, level: `0`, startTime: '2024-07-19T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Angela Jauregui', artistTwo: '', flag: true },
            { id: 403, group: [401,402,403,404,405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'Cuban Movement Practise', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '14:15 - 15:15', room: `Room 03`, level: `0`, startTime: '2024-07-19T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
            { id: 404, group: [401,402,403,404,405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Rumba Columbia', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '14:15 - 15:15', room: `Room 04`, level: `2`, startTime: '2024-07-19T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
            { id: 405, group: [401,402,403,404,405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lucas', sessionMainTitle: 'Rueda Transiciones', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '14:15 - 15:15', room: `Room 05`, level: `1`, startTime: '2024-07-19T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lucas Flemming', artistTwo: '', flag: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 501, group: [501,502,503,504,505], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lucas / Kimmy', sessionMainTitle: 'Casino Transiciones', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:30 - 16:30', room: `Room 01`, level: `1`, startTime: '2024-07-19T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lucas Flemming', artistTwo: '', flag: false },
            { id: 502, group: [501,502,503,504,505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio', sessionMainTitle: 'Rumba Columbia', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:30 - 16:30', room: `Room 02`, level: `1`, startTime: '2024-07-19T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },
            { id: 503, group: [501,502,503,504,505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lynet', sessionMainTitle: 'Afro-Contemporary', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:30 - 16:30', room: `Room 03`, level: `0`, startTime: '2024-07-19T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lynet Rubio', artistTwo: '', flag: true },
            { id: 504, group: [501,502,503,504,505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Lumbanche', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:30 - 16:30', room: `Room 04`, level: `1`, startTime: '2024-07-19T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },
            { id: 505, group: [501,502,503,504,505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Advanced Caminando', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:30 - 16:30', room: `Room 05`, level: `2`, startTime: '2024-07-19T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 601, group: [601,602,603,604,605], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio // Angela', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '16:45 - 17:45', room: `Room 01`, level: `0`, startTime: '2024-07-19T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
            { id: 602, group: [601,602,603,604,605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Wendy', sessionMainTitle: 'Reggaeton', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '16:45 - 17:45', room: `Room 02`, level: `0`, startTime: '2024-07-19T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Wendy Solanch', artistTwo: '', flag: true },
            { id: 603, group: [601,602,603,604,605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jonas (Tanzpause)', sessionMainTitle: 'An Interactive Journey: Roots of Timba', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '16:45 - 17:45', room: `Room 03`, level: ``, startTime: '2024-07-19T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Jonas Reichert', artistTwo: '', flag: true },
            { id: 604, group: [601,602,603,604,605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'Palo Genérico', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '16:45 - 17:45', room: `Room 04`, level: `0`, startTime: '2024-07-19T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
            { id: 605, group: [601,602,603,604,605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Hidden Structures', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '16:45 - 17:45', room: `Room 05`, level: `2`, startTime: '2024-07-19T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            { id: 110, group: [], groupTitle: 'Berlin Experience', groupSubtitle: '', itemType: 'type2', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Berlin Experience', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '13:00', room: ``, level: ``, startTime: '2024-07-19T13:00', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 111, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Berlin Highlights City Tour with Rueda de Casino', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '13:00 - 15:00', room: ``, level: ``, startTime: '2024-07-19T13:00', endTime: '2024-06-14T15:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 112, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: ``, sessionMainTitle: 'Afternoon Social', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '15:00 - 18:00', room: ``, level: ``, startTime: '2024-07-19T15:00', endTime: '2024-06-15T18:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 113, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Beginner Bootcamp', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '18:00 - 20:30', room: ``, level: ``, startTime: '2024-06-15T18:00', endTime: '2024-06-15T20:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 114, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Pre-Party Workshop', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '21:00 - 22:00', room: ``, level: ``, startTime: '2024-06-15T21:00', endTime: '2024-06-15T22:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 115, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Welcome Party', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '22:00 - 03:00', room: ``, level: ``, startTime: '2024-06-15T22:00', endTime: '2024-06-15T03:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
            { id: 116, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Fri, July 19th 2024', time: '', room: ``, level: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
        ]


    //this is formatted in LauncherController during initialize() based on dataRaw;
    static dataArtistsList = null;
    static dataScheduleListsByDay = null;
}

export default DataModel;