export const modelInitStaticOverwrite =
{
  "modelVersion": 1149,
  "festivalName": "WELLBEING",
  "modelRemoteGetModelUrl": "https://5sw1zcun82.execute-api.us-west-1.amazonaws.com/wellbeingModelContent",
  "modelRemoteVersionCheckUrl": "https://5sw1zcun82.execute-api.us-west-1.amazonaws.com/wellbeingModelVersion",
  "modelRemoteUpdateInterval": 10000,
  "happeningNowUpdateInterval": 30000,
  "dataTicketSales": {
    "earlyBirdStartTimeString": "2024-07-21T05:00:00.000"
  },
  "dataArtists": {
    "Dr. Brian Hernandez": {
      "fullName": "Dr. Brian Hernandez",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Dr. Brian Hernandez is a licensed chiropractor based in San Francisco, California, dedicated to helping individuals achieve optimal health and wellness through gentle, effective spinal care. With a passion for empowering patients to take control of their health, Dr. Hernandez offers comprehensive chiropractic services, including free spinal assessments, to identify and address underlying issues.\n\nThrough his expert care, Dr. Hernandez aims to relieve pain, improve posture, and enhance overall quality of life. By combining cutting-edge techniques with a holistic approach, Dr. Hernandez creates a supportive environment for individuals to heal, grow, and thrive.",
      "shortBio": "",
      "facebook": "",
      "portrait": "dr_brian_hernandez",
      "email": "hernandezchiropractic@hotmail.com",
      "phone": ""
    },
    "Christine Lu Singh": {
      "fullName": "Christine Lu Singh",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "@breathewithtine",
      "web": "",
      "bio": "Christine Lu Singh is a holistic wellness expert based in San Francisco, California, offering Reiki-infused sound healing and aromatherapy sessions. With a deep passion for energy healing and vibrational medicine, Christine creates sacred spaces for individuals to relax, recharge, and reconnect with their inner selves.\n\nCombining her training in Reiki, sound healing, and aromatherapy, Christine crafts unique sessions that harmonize the body, mind, and spirit. Her approach is intuitive, compassionate, and tailored to each individual's needs, allowing for a profoundly relaxing and transformative experience.\n\nChristine's sessions often feature the use of singing bowls, tuning forks, and essential oils, carefully selected to promote balance, calm, and well-being. Her Reiki-infused sound healing and aromatherapy practice is a sanctuary for those seeking relaxation, stress relief, and spiritual growth.\n\nLet me know if you'd like me to make any changes!",
      "shortBio": "",
      "facebook": "",
      "portrait": "christine_lu_singh",
      "email": "hello@breathewithtine.com",
      "phone": ""
    },
    "Chuck Rosenthal": {
      "fullName": "Chuck Rosenthal",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "@thelogosmethod",
      "web": "https://thelogosmethod.com/",
      "bio": "Chuck Rosenthal is a gifted sound healer, musician, and meditation guide based in San Francisco, California. With over a decade of experience in the healing arts, Chuck has established himself as a leading figure in the Bay Area's vibrant sound healing community.\n\nChuck's journey into sound healing began with his own personal experiences of transformation through music and meditation. He discovered the profound effects of sound on the mind, body, and spirit, and dedicated himself to studying the ancient traditions of sound healing. He has trained extensively in the use of gongs, singing bowls, tuning forks, and other sound healing instruments, and has developed a unique approach that blends traditional techniques with modern innovations.\n\nAs a sound healer, Chuck creates immersive, transportive experiences that invite listeners to relax, recharge, and reconnect with their inner selves. His sound baths and meditation sessions have been praised for their ability to calm the mind, soothe the body, and awaken the spirit. Chuck has worked with individuals, groups, and organizations, and has led sound healing workshops and retreats throughout the Bay Area.\n\nChuck's approach to sound healing is holistic, incorporating elements of meditation, breathwork, and energy healing into his sessions. He believes that sound has the power to awaken our deepest potential, and that by tuning into the vibrations of the universe, we can cultivate greater harmony, balance, and well-being in our lives.\n\nWhen not leading sound healing sessions, Chuck can be found composing music, exploring the natural beauty of the Bay Area, or studying the latest research on the healing effects of sound. He is passionate about sharing the gifts of sound healing with others, and is committed to creating a more harmonious, compassionate world, one vibration at a time.",
      "shortBio": "",
      "facebook": "",
      "portrait": "chuck_rosenthal",
      "email": "thelogosmethod@gmail.com",
      "phone": ""
    },
    "Emiko Oye": {
      "fullName": "Emiko Oye",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Emiko Oye is a dedicated and compassionate wellness expert specializing in hand and neck health, based in San Francisco, California. With over 10 years of experience in the field of manual therapy and movement education, Emiko has established herself as a leading authority on easy, effective exercises for maintaining optimal hand and neck function.\n\nEmiko's passion for hand and neck health began with her own experiences of pain and discomfort, which she overcame through a combination of manual therapy, exercise, and lifestyle changes. She went on to study manual therapy, anatomy, and movement science, and developed a unique approach that emphasizes gentle, accessible exercises for everyday people.\n\nAs a wellness expert, Emiko teaches workshops, classes, and private sessions focused on hand and neck health, sharing her expertise with individuals from all walks of life. Her exercises are designed to be easy to learn, simple to practice, and adaptable to any lifestyle. Emiko has worked with students of all ages, from children to seniors, and has experience teaching exercises for specific needs, such as injury rehabilitation, stress relief, and improved range of motion.\n\nEmiko's approach to hand and neck health is holistic, incorporating elements of anatomy, physiology, and mindfulness into her teaching. She believes that by cultivating awareness and care for our hands and necks, we can improve our overall well-being, enhance our productivity, and live more fulfilling lives.\n\nWhen not teaching, Emiko can be found exploring the natural beauty of the Bay Area, practicing yoga, or studying the latest research on manual therapy and movement science. She is passionate about empowering others to take charge of their hand and neck health, and is committed to making wellness accessible to everyone.\n\nNote: I assumed Emiko Oye is a female, if Emiko is a male, I can adjust the pronouns accordingly.",
      "shortBio": "",
      "facebook": "",
      "portrait": "emiko_oye",
      "email": "emiko@emikooyoga.com",
      "phone": ""
    },
    "Erynne Elkins": {
      "fullName": "Erynne Elkins",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "https://digitalhippy70.com",
      "bio": "Erynne Elkins is a San Francisco-based yoga teacher specializing in breathwork classes. With a passion for pranayama, Erynne guides students in the transformative power of conscious breathing, calming the nervous system, balancing emotions, and awakening the full potential of the human spirit.\n\nHer classes feature innovative breathwork techniques, carefully sequenced to promote relaxation, focus, and inner peace. Erynne's approach is holistic, incorporating yoga philosophy, anatomy, and energy healing into her teaching.\n\nBy sharing the gifts of breathwork, Erynne aims to create a more calm, compassionate, and connected world, one breath at a time.",
      "shortBio": "",
      "facebook": "",
      "portrait": "erynne_elkins",
      "email": "erynne@digitalhippy70.com",
      "phone": ""
    },
    "Gautam Mulchandani": {
      "fullName": "Gautam Mulchandani",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024",
        "02-2024"
      ],
      "insta": "@gemsofclaritysocial.com",
      "web": "https://gemsofclarity.com",
      "bio": "Gautam Mulchandani is a San Francisco-based yoga teacher and intuitive reader, guiding individuals on their journey of self-discovery and spiritual growth. With a compassionate and empathetic approach, Gautam offers intuitive readings that provide insight, clarity, and guidance for navigating life's challenges.\n\nBlending his knowledge of yoga philosophy, energy healing, and intuitive wisdom, Gautam creates a safe and supportive space for individuals to explore their inner world, awaken their potential, and connect with their deepest selves.\n\nThrough his intuitive readings and yoga teachings, Gautam aims to empower others to live more authentic, meaningful, and fulfilling lives.",
      "shortBio": "",
      "facebook": "",
      "portrait": "gautam_mulchandani",
      "email": "gmulchandani@gmail.com",
      "phone": "415-699-4263"
    },
    "Gogo Zoger": {
      "fullName": "Gogo Zoger",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "@gogoflow",
      "web": "https://www.gogoflowpodcast.com",
      "bio": "Gogo Zoger is a San Francisco-based yoga teacher and mindfulness expert, dedicated to helping others calm their minds and unlock their full potential. With her signature teaching style, Gogoflow, Gogo guides students in taking a pause from overthinking, cultivating clarity, and reconnecting with their inner selves.\n\nGogoflow, a unique blend of breathwork, movement, and meditation, is designed to quiet the mind, soothe the nervous system, and awaken a sense of inner peace. By sharing her wisdom and expertise, Gogo aims to empower others to break free from the cycle of overthinking and live more present, authentic, and fulfilling lives.",
      "shortBio": "",
      "facebook": "",
      "portrait": "gogo_zoger",
      "email": "onlyonegogoz@gmail.com",
      "phone": ""
    },
    "Jerry Cuffey": {
      "fullName": "Jerry Cuffey",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024",
        "02-2024"
      ],
      "insta": "",
      "web": "yelp.com",
      "bio": "Jerry Cuffey is a licensed massage therapist based in San Francisco, California, specializing in chair massage. With a gentle and intuitive touch, Jerry provides stress-relieving and tension-melting chair massages, tailored to ease muscle strain, improve circulation, and promote overall well-being.\n\nJerry's chair massage sessions are designed to be convenient, accessible, and adaptable to any lifestyle, allowing individuals to take a moment for self-care and relaxation in the midst of a busy day. With a focus on comfort and relaxation, Jerry helps clients unwind, recharge, and feel their best.",
      "shortBio": "",
      "facebook": "",
      "portrait": "jerry_cuffey",
      "email": "undermyhandsbyjerry@gmail.com",
      "phone": ""
    },
    "Kamelle Mills": {
      "fullName": "Kamelle Mills",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "@kamellemills",
      "web": "https://www.instagram.com/kamellemills",
      "bio": "Kamelle Mills is a compassionate and experienced facilitator based in San Francisco, California, dedicated to creating safe and inclusive spaces for connection and growth. As a conversation circle leader, Kamelle guides groups in exploring meaningful topics, fostering empathy, and cultivating community.\n\nDuring the SF Wellbeing Fair, Kamelle will lead a conversation circle, inviting participants to share their thoughts, listen deeply, and connect with others. Her warm and non-judgmental approach creates a supportive environment for individuals to explore their well-being, share their experiences, and build meaningful connections with others.",
      "shortBio": "",
      "facebook": "",
      "portrait": "kamelle_mills",
      "email": "kamelle@enbeyes.com",
      "phone": ""
    },
    "Lars Kallman": {
      "fullName": "Lars Kallman",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024",
        "02-2024"
      ],
      "insta": "",
      "web": "yelp.com",
      "bio": "Lars Kallman is a licensed massage therapist and Gestalt practitioner based in San Francisco, California, offering deep bodywork and transformative sessions. With a focus on holistic healing, Lars combines intuitive bodywork, breath awareness, and Gestalt principles to guide clients in releasing tension, awakening awareness, and integrating body, mind, and spirit.\n\nThrough his unique approach, Lars creates a safe and supportive environment for individuals to explore their inner world, process emotions, and cultivate greater self-awareness. His deep bodywork and Gestalt sessions invite clients to embark on a journey of self-discovery, empowerment, and profound transformation.",
      "shortBio": "",
      "facebook": "",
      "portrait": "lars_kallman",
      "email": "kallmanlars@gmail.com",
      "phone": ""
    },
    "Lydia Real": {
      "fullName": "Lydia Real",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024",
        "02-2024"
      ],
      "insta": " ",
      "web": "https://sistahplanet.com",
      "bio": "Lydia Real is a body positivity advocate and wellness expert based in San Francisco, California, dedicated to empowering individuals to cultivate a positive and compassionate relationship with their bodies. With her message of Positive Body Talk, Lydia encourages others to turn down the noise of self-criticism and internalize self-love, self-acceptance, and self-care.\n\nThrough workshops, coaching, and community engagement, Lydia provides tools and support for individuals to rewire their mindset, challenge societal beauty standards, and embrace their unique beauty and worth. By promoting Positive Body Talk, Lydia aims to create a more inclusive and supportive environment where everyone can thrive and celebrate their individuality.",
      "shortBio": "",
      "facebook": "",
      "portrait": "lydia_real",
      "email": "sistahplanet@gmail.com",
      "phone": ""
    },
    "Mané": {
      "fullName": "Mané",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "https://www.nathiebi.com",
      "bio": "Mané is a passionate artisan and wellness enthusiast based in San Francisco, California, dedicated to crafting handmade, organic shea butter soaps and lotions that nourish and pamper the skin. With a focus on natural ingredients and sustainable practices, Mané creates small-batch, artisanal products that promote healthy, glowing skin and a deeper connection with nature.\n\nInspired by traditional African recipes and infused with love and care, Mané's shea butter creations are designed to moisturize, soothe, and protect the skin, while also promoting relaxation and self-care. By sharing her handmade products, Mané aims to spread joy, wellness, and a sense of community, one bar of soap at a time.",
      "shortBio": "",
      "facebook": "",
      "portrait": "mane",
      "email": "soapsbymane@gmail.com",
      "phone": ""
    },
    "Meghan Johnson": {
      "fullName": "Meghan Johnson",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024",
        "02-2024"
      ],
      "insta": "",
      "web": "https://stclaudehealingarts.com",
      "bio": "Meghan Johnson is a licensed massage therapist based in San Francisco, California, specializing in chair massage therapy. With a warm and intuitive touch, Meghan provides relaxing and rejuvenating chair massages, tailored to ease tension, soothe muscles, and calm the mind.\n\nThrough her skilled and gentle technique, Meghan helps individuals release physical and mental stress, promoting a sense of calm, clarity, and overall well-being. Whether you're looking to unwind, improve your focus, or simply indulge in some self-care, Meghan's chair massages offer a peaceful oasis in the midst of a busy day.",
      "shortBio": "",
      "facebook": "",
      "portrait": "meghan_johnson",
      "email": "stclaudemassage@gmail.com",
      "phone": ""
    },
    "Mirabai Warkulwiz": {
      "fullName": "Mirabai Warkulwiz",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Mirabai Warkulwiz is a devoted Bhakti Yoga teacher and Kirtan leader based in San Francisco, California. With a heart full of love and devotion, Mirabai shares the ancient traditions of Bhakti Yoga, guiding others on a journey of self-discovery, spiritual growth, and connection with the divine.\n\nThrough her soulful Kirtan chanting and inspiring teachings, Mirabai creates a sacred space for individuals to experience the transformative power of love, compassion, and community. Her passion is to help others awaken their inner light, cultivate inner peace, and embody the joy and beauty of Bhakti Yoga.",
      "shortBio": "",
      "facebook": "",
      "portrait": "mirabai_warkulwiz",
      "email": "mirabaiyoga@hotmail.com",
      "phone": ""
    },
    "Nirel Salazar": {
      "fullName": "Nirel Salazar",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "https://www.nireltheyogini.com",
      "bio": "Nirel Salazar is a certified Reiki practitioner and Somatic Sound Healing expert based in San Francisco, California. With a gentle and intuitive approach, Nirel offers energy balancing sessions that harmonize body, mind, and spirit.\n\nThrough the subtle yet powerful modalities of Reiki and Somatic Sound Healing, Nirel creates a safe and supportive environment for individuals to release tension, calm their nervous system, and awaken their inner vitality. Her sessions are tailored to each client's unique needs, promoting relaxation, self-awareness, and overall well-being.",
      "shortBio": "",
      "facebook": "",
      "portrait": "nirel_salazar",
      "email": "hello@nireltheyogini.com",
      "phone": ""
    },
    "Robert Bray": {
      "fullName": "Robert Bray",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Robert Bray is a certified nature therapist and forest bathing guide based in San Francisco, California. With a deep passion for connecting people with nature, Robert leads informative and immersive forest bathing walks, inviting individuals to slow down, awaken their senses, and cultivate a sense of well-being and connection with the natural world.\n\nThrough his guided walks, Robert shares his knowledge of local flora, fauna, and ecology, while also encouraging participants to tune into the healing properties of nature, reduce stress, and boost their mood and creativity. By fostering a deeper appreciation for the natural world, Robert aims to inspire a sense of wonder, awe, and environmental stewardship.",
      "shortBio": "",
      "facebook": "",
      "portrait": "robert_bray",
      "email": "robtbray@sbcglobal.net",
      "phone": ""
    },
    "Suzannah Weening": {
      "fullName": "Suzannah Weening",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Suzannah Weening is a compassionate midwife and birth photographer based in San Francisco, California, dedicated to empowering women and families through pregnancy, birth, and beyond. With a warm and non-intrusive approach, Suzannah captures the intimate moments of childbirth and parenthood through her photography, preserving memories and telling stories of love, strength, and transformation.\n\nAs a midwife, Suzannah provides holistic care and support to expectant mothers, guiding them through the journey of pregnancy, labor, and postpartum. Her passion is to create a safe, nurturing environment where women can trust their bodies, make informed choices, and experience the beauty and power of birth.",
      "shortBio": "",
      "facebook": "",
      "portrait": "suzannah_weening",
      "email": "suzannah88@gmaill.com",
      "phone": ""
    },
    "Taylor Bowman": {
      "fullName": "Taylor Bowman",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "Taylor Bowman is a creative enthusiast and wellness advocate based in San Francisco, California, passionate about fostering self-expression and mindfulness through art-making. As the leader of the Crafty Corner during the SF Wellbeing Fair, Taylor invites participants to explore their imagination and unwind through various craft activities, such as painting, drawing, and DIY projects.\n\nWith a warm and encouraging approach, Taylor creates a welcoming space for individuals to tap into their creativity, relax, and connect with others. By combining art, mindfulness, and community, Taylor aims to inspire joy, self-care, and a sense of connection among participants.",
      "shortBio": "",
      "facebook": "",
      "portrait": "taylor_bowman",
      "email": "taylor.bowman9573@gmail.com",
      "phone": ""
    },
    "TendWell Collective": {
      "fullName": "TendWell Collective",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "TendWell Collective is a community-driven initiative based in San Francisco, California, dedicated to cultivating embodied wellness and creative expression. Through their signature offering, \"Finding Refuge,\" TendWell Collective provides a sacred space for individuals to explore the intersection of social justice, mindfulness, and art.\n\nTheir Embodied Reading series invites participants to engage with literature and poetry through somatic practices, fostering a deeper connection with oneself, others, and the world. By integrating mindfulness, creativity, and social awareness, TendWell Collective aims to create a refuge for individuals to heal, grow, and thrive.",
      "shortBio": "",
      "facebook": "",
      "portrait": "tendwell_collective",
      "email": "hello@tendwellcollective.com",
      "phone": ""
    },
    "Tina Pham": {
      "fullName": "Tina Pham",
      "pronouns": "she/they",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "https://www.persimmonacupuncture.com",
      "bio": "Tina Pham is a Qigong practitioner and Chinese Medicine enthusiast based in San Francisco, California, dedicated to empowering individuals to cultivate balance and harmony in their lives. With a focus on anxiety relief and autumn wellness, Tina shares the ancient wisdom of Qigong and Chinese Medicine to help others navigate the complexities of modern life.\n\nThrough gentle movements, breathwork, and meditation, Tina's Qigong practice invites individuals to calm their minds, soothe their nerves, and connect with their inner selves. By honoring the rhythms of nature and the seasons, Tina's approach to autumn wellness offers practical tips and self-care strategies for thriving during times of transition.",
      "shortBio": "",
      "facebook": "",
      "portrait": "tina_pham",
      "email": "tina@persimmonacupuncture.com",
      "phone": ""
    },
    "Adrien Joyner": {
      "fullName": "Adrien Joyner",
      "pronouns": "they/them",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "adrien_joyner",
      "email": "chakrarainbowyoga@gmail.com",
      "phone": ""
    },
    "Alex Castro": {
      "fullName": "Alex Castro",
      "pronouns": "She/Her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "alex_castro",
      "email": "alexcastro@lgbtqmindfulness.com",
      "phone": ""
    },
    "Alexandria Nichandros": {
      "fullName": "Alexandria Nichandros",
      "pronouns": "She/Her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "alexandria_nichandros",
      "email": "2468dance@gmail.com",
      "phone": ""
    },
    "Bex Mui": {
      "fullName": "Bex Mui",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "bex_mui",
      "email": "bex@houseofourqueer.com",
      "phone": ""
    },
    "David Khalili": {
      "fullName": "David Khalili",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "david_khalili",
      "email": "david@rousetherapy.com",
      "phone": ""
    },
    "Den Bremond": {
      "fullName": "Den Bremond",
      "pronouns": "she/her/they",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "den_bremond",
      "email": "denbremond@gmail.com",
      "phone": ""
    },
    "Dhiraj Korwani": {
      "fullName": "Dhiraj Korwani",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "dhiraj_korwani",
      "email": "djkorwani@gmail.com,",
      "phone": "415-351-8013"
    },
    "Jeanna Eichenbaum": {
      "fullName": "Jeanna Eichenbaum",
      "pronouns": "they/them/elle",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "jeanna_eichenbaum",
      "email": "jeannamind@yahoo.com",
      "phone": ""
    },
    "Ki Charles": {
      "fullName": "Ki Charles",
      "pronouns": "They/She",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "ki_charles",
      "email": "ki@haumsf.com",
      "phone": ""
    },
    "Kramer Dahl": {
      "fullName": "Kramer Dahl",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "kramer_dahl",
      "email": "kramer.dahl90@gmail.com",
      "phone": "650-200-9079"
    },
    "Olivier De Wulf": {
      "fullName": "Olivier De Wulf",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "olivier_de_wulf",
      "email": "info@neurasonic.com",
      "phone": ""
    },
    "Phil Deem": {
      "fullName": "Phil Deem",
      "pronouns": "he/him",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "phil_deem",
      "email": "phil@spirit-treeapothecary.com",
      "phone": ""
    },
    "Sophia Lin": {
      "fullName": "Sophia Lin",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "sophia_lin",
      "email": "sophialin499@gmail.com",
      "phone": ""
    },
    "Susan Sullivan": {
      "fullName": "Susan Sullivan",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": " ",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "susan_sullivan",
      "email": "susansullivanis@gmail.com",
      "phone": ""
    },
    "Tijanna Eaton": {
      "fullName": "Tijanna Eaton",
      "pronouns": "she/her",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "02-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "",
      "shortBio": "",
      "facebook": "",
      "portrait": "tijanna_eaton",
      "email": "thatsbennett2u@gmail.com",
      "phone": ""
    },
    "Nicola Bosco": {
      "fullName": "Nicola Bosco",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "was born.. ",
      "shortBio": "",
      "facebook": "",
      "portrait": "nicola_bosco",
      "email": "",
      "phone": ""
    },
    "Andrea Stern": {
      "fullName": "Andrea Stern",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "was born.. ",
      "shortBio": "",
      "facebook": "",
      "portrait": "andrea_stern",
      "email": "",
      "phone": ""
    },
    "Marc Morozumi": {
      "fullName": "Marc Morozumi",
      "pronouns": "",
      "artistLocation": "",
      "artistCompany": "",
      "editionData": [
        "03-2024"
      ],
      "insta": "",
      "web": "",
      "bio": "was born.. ",
      "shortBio": "",
      "facebook": "",
      "portrait": "marc_morozumi",
      "email": "",
      "phone": ""
    }
  },
  "dataScheduleRaw": [
    {
      "id": "48aaa69e8eb8bd6537c08a5326f664d6",
      "itemType": "type2",
      "artistName": "Nicola Bosco",
      "sessionMainTitle": "Welcome to attendees from our Autumn Abundance host!",
      "time": "",
      "room": "Opening",
      "level": "",
      "group": [],
      "groupTitle": "Opening",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Nicola Bosco",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "0f68568d33f351b0ec4c269e3fedb5a8",
      "itemType": "type2",
      "artistName": "Andrea Stern",
      "sessionMainTitle": "Co-founder of TendWell Collective and Collaborator in the SF WBF",
      "time": "",
      "room": "Opening",
      "level": "",
      "group": [],
      "groupTitle": "Opening",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Andrea Stern",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "7708770154a0f8fea805e9a0360eb24e",
      "itemType": "type2",
      "artistName": "Marc Morozumi",
      "sessionMainTitle": "Founder and Owner of Mukunda Studio and Presenter of the SF WBF",
      "time": "",
      "room": "Opening",
      "level": "",
      "group": [],
      "groupTitle": "Opening",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Marc Morozumi",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "3c5f0fd6ffb1dd45f1c4f0fa01966503",
      "itemType": "type2",
      "artistName": "Kamelle Mills",
      "sessionMainTitle": "Grand Host Welcome",
      "time": "",
      "room": "Opening",
      "level": "",
      "group": [],
      "groupTitle": "Opening",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Kamelle Mills",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "60a32f5faa5302527718928f28103ec1",
      "itemType": "type1",
      "artistName": "Gogo Zoger",
      "sessionMainTitle": "Take a Pause From Overthinking - gogoflow Yoga",
      "time": "1:00-1:30pm",
      "room": "Group Class",
      "level": "",
      "group": [
        "60a32f5faa5302527718928f28103ec1",
        "041002ff697e9a60e41a1c5daeb9437e",
        "ae13e0992b99c7db7021f72810b9e03e"
      ],
      "groupTitle": "Group Class",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:00pm",
      "endTime": "1:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Gogo Zoger",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "eb603860d03004651c75294a43f01683",
      "itemType": "type1",
      "artistName": "Christine Lu Singh",
      "sessionMainTitle": "Reiki-Infused Sound Healing & Aromatherapy",
      "time": "1:45-2:15pm",
      "room": "Group Class",
      "level": "",
      "group": [
        "eb603860d03004651c75294a43f01683",
        "655e6b81f62b969837f28b6a183e2757",
        "84b3bba80ff1f778c34c3ea95526d2f0"
      ],
      "groupTitle": "Group Class",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:45pm",
      "endTime": "2:15pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Christine Lu Singh",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "c874cbe1d329de443aa4e160be462c0c",
      "itemType": "type1",
      "artistName": "Emiko Oye",
      "sessionMainTitle": "Easy Exercises for Hands, Head and Neck Health",
      "time": "2:30-3pm",
      "room": "Group Class",
      "level": "",
      "group": [
        "c874cbe1d329de443aa4e160be462c0c",
        "13b859bcec5e064aa8e79112a8f4ada8"
      ],
      "groupTitle": "Group Class",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "2:30pm",
      "endTime": "3pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Emiko Oye",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "41dfc83d10c5de7e04881bcf01c0b40e",
      "itemType": "type1",
      "artistName": "Erynne Elkins",
      "sessionMainTitle": "Transformative Breathwork",
      "time": "3:15-3:45pm",
      "room": "Group Class",
      "level": "",
      "group": [
        "41dfc83d10c5de7e04881bcf01c0b40e",
        "1e1cb04b93d251864aebfad733966867",
        "fb7bd60a1f2ce8c5d57da4d55153afc6"
      ],
      "groupTitle": "Group Class",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "3:15pm",
      "endTime": "3:45pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Erynne Elkins",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "44fd835bdb68fa479ada5f243e8682fd",
      "itemType": "type1",
      "artistName": "Chuck Rosenthal",
      "sessionMainTitle": "Therapeutic Sound Journeys with Reiki",
      "time": "4-4:30pm",
      "room": "Group Class",
      "level": "",
      "group": [
        "44fd835bdb68fa479ada5f243e8682fd",
        "645006a3f617b0ac44ef01bf752cb4a1"
      ],
      "groupTitle": "Group Class",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "4pm",
      "endTime": "4:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Chuck Rosenthal",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "e875f1a2adad6629d5677f445221284f",
      "itemType": "type3",
      "artistName": "Gautam Mulchandani",
      "sessionMainTitle": "Intuitive Readings",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Gautam Mulchandani",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "3425b89d9cbb43011c81755705371511",
      "itemType": "type3",
      "artistName": "Chuck Rosenthal",
      "sessionMainTitle": "Therapeutic Sound Journeys with Reiki",
      "time": "4-4:30pm",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "4pm",
      "endTime": "4:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Chuck Rosenthal",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "56b4e41bd982cb83104bdc380fa7811f",
      "itemType": "type3",
      "artistName": "Nirel Salazar",
      "sessionMainTitle": "Energy balancing sessions through Reiki and Somatic Sound Healing",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Nirel Salazar",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "1a4ef88ecf3acb44ff29257550bab9a4",
      "itemType": "type3",
      "artistName": "Erynne Elkins",
      "sessionMainTitle": "Learn about Transformative Breathwork",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Erynne Elkins",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "211e154258aef20d52674f4f3112626d",
      "itemType": "type3",
      "artistName": "Tina Pham",
      "sessionMainTitle": "Ear Acupressure and Herbal Tea Sampling",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Tina Pham",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "5ead93d8a7ecf9333cb38385e8a1d01e",
      "itemType": "type3",
      "artistName": "Dr. Brian Hernandez",
      "sessionMainTitle": "Free spinal screening with promotional signup discount",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Dr. Brian Hernandez",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "3362fe14b0de75e8a08e49f77f930055",
      "itemType": "type3",
      "artistName": "Mané",
      "sessionMainTitle": "Handmade Shea butter soaps and lotion",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Mané",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "5a8f2e8beb95cd9fdbdff1a22a908cde",
      "itemType": "type3",
      "artistName": "Lydia Real",
      "sessionMainTitle": "Goddess figurines and original body positive feminine art",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Lydia Real",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "82f24c5939ba152344d3db96d5314809",
      "itemType": "type3",
      "artistName": "Suzannah Weening",
      "sessionMainTitle": "Mid-wife and birth photographer",
      "time": "",
      "room": "Main Fair Room",
      "level": "",
      "group": [],
      "groupTitle": "Main Fair Room",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Suzannah Weening",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "041002ff697e9a60e41a1c5daeb9437e",
      "itemType": "type1",
      "artistName": "Mirabai Warkulwiz",
      "sessionMainTitle": "Bhakti Ocean",
      "time": "1:00-1:30pm",
      "room": "Conversation Circles",
      "level": "",
      "group": [
        "60a32f5faa5302527718928f28103ec1",
        "041002ff697e9a60e41a1c5daeb9437e",
        "ae13e0992b99c7db7021f72810b9e03e"
      ],
      "groupTitle": "Conversation Circles",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:00pm",
      "endTime": "1:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Mirabai Warkulwiz",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "655e6b81f62b969837f28b6a183e2757",
      "itemType": "type1",
      "artistName": "Kamelle Mills",
      "sessionMainTitle": "enbeyes - No Bullsh!t :) (Ask about Prosperity Practice)",
      "time": "1:45-2:15pm",
      "room": "Conversation Circles",
      "level": "",
      "group": [
        "eb603860d03004651c75294a43f01683",
        "655e6b81f62b969837f28b6a183e2757",
        "84b3bba80ff1f778c34c3ea95526d2f0"
      ],
      "groupTitle": "Conversation Circles",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:45pm",
      "endTime": "2:15pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Kamelle Mills",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "1e1cb04b93d251864aebfad733966867",
      "itemType": "type1",
      "artistName": "Lydia Real",
      "sessionMainTitle": "Positive Body Talk - Turning Down the Noise!",
      "time": "3:15-3:45pm",
      "room": "Conversation Circles",
      "level": "",
      "group": [
        "41dfc83d10c5de7e04881bcf01c0b40e",
        "1e1cb04b93d251864aebfad733966867",
        "fb7bd60a1f2ce8c5d57da4d55153afc6"
      ],
      "groupTitle": "Conversation Circles",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "3:15pm",
      "endTime": "3:45pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Lydia Real",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "645006a3f617b0ac44ef01bf752cb4a1",
      "itemType": "type1",
      "artistName": "Marc Morozumi",
      "sessionMainTitle": "We Are More Than Our Stories",
      "time": "4-4:30pm",
      "room": "Conversation Circles",
      "level": "",
      "group": [
        "44fd835bdb68fa479ada5f243e8682fd",
        "645006a3f617b0ac44ef01bf752cb4a1"
      ],
      "groupTitle": "Conversation Circles",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "4pm",
      "endTime": "4:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Marc Morozumi",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "943fd4185f001806cb57be4115d4be07",
      "itemType": "type4",
      "artistName": "Meghan Johnson",
      "sessionMainTitle": "Chair Massage",
      "time": "",
      "room": "Massage",
      "level": "",
      "group": [],
      "groupTitle": "Massage",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Meghan Johnson",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "1eeda4ae39f7fb04fbb87eacc523f8d2",
      "itemType": "type4",
      "artistName": "Jerry Cuffey",
      "sessionMainTitle": "Chair Massage - Japanese Acupressure Techniques",
      "time": "",
      "room": "Massage",
      "level": "",
      "group": [],
      "groupTitle": "Massage",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Jerry Cuffey",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "b3f09cb8696993a8ce8b0fcd26164aee",
      "itemType": "type4",
      "artistName": "Lars Kallman",
      "sessionMainTitle": "Deep bodywork and gestalt",
      "time": "",
      "room": "Massage",
      "level": "",
      "group": [],
      "groupTitle": "Massage",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Lars Kallman",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "0b4a9236b87045ab2a8980bce37d8b67",
      "itemType": "type4",
      "artistName": "Taylor Bowman",
      "sessionMainTitle": "Crafty Corner",
      "time": "",
      "room": "Crafty Corner",
      "level": "",
      "group": [],
      "groupTitle": "Crafty Corner",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Taylor Bowman",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "ae13e0992b99c7db7021f72810b9e03e",
      "itemType": "type1",
      "artistName": "Taylor Bowman",
      "sessionMainTitle": "Community Mandala on the lawn",
      "time": "1:00-1:30pm",
      "room": "Outside",
      "level": "",
      "group": [
        "60a32f5faa5302527718928f28103ec1",
        "041002ff697e9a60e41a1c5daeb9437e",
        "ae13e0992b99c7db7021f72810b9e03e"
      ],
      "groupTitle": "Outside",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:00pm",
      "endTime": "1:30pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Taylor Bowman",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "84b3bba80ff1f778c34c3ea95526d2f0",
      "itemType": "type1",
      "artistName": "Tina Pham",
      "sessionMainTitle": "Qigong for Anxiety",
      "time": "1:45-2:15pm",
      "room": "Outside",
      "level": "",
      "group": [
        "eb603860d03004651c75294a43f01683",
        "655e6b81f62b969837f28b6a183e2757",
        "84b3bba80ff1f778c34c3ea95526d2f0"
      ],
      "groupTitle": "Outside",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "1:45pm",
      "endTime": "2:15pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Tina Pham",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "13b859bcec5e064aa8e79112a8f4ada8",
      "itemType": "type1",
      "artistName": "Robert Bray",
      "sessionMainTitle": "Forest bathing/informative nature walk",
      "time": "2:30-3pm",
      "room": "Outside",
      "level": "",
      "group": [
        "c874cbe1d329de443aa4e160be462c0c",
        "13b859bcec5e064aa8e79112a8f4ada8"
      ],
      "groupTitle": "Outside",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "2:30pm",
      "endTime": "3pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Robert Bray",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "fb7bd60a1f2ce8c5d57da4d55153afc6",
      "itemType": "type1",
      "artistName": "TendWell Collective",
      "sessionMainTitle": "Finding Refuge, Embodied Reading",
      "time": "3:15-3:45pm",
      "room": "Outside",
      "level": "",
      "group": [
        "41dfc83d10c5de7e04881bcf01c0b40e",
        "1e1cb04b93d251864aebfad733966867",
        "fb7bd60a1f2ce8c5d57da4d55153afc6"
      ],
      "groupTitle": "Outside",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "3:15pm",
      "endTime": "3:45pm",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "TendWell Collective",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "76e3fb71691ade3084d24ac98537500d",
      "itemType": "type2",
      "artistName": "Nicola Bosco",
      "sessionMainTitle": "",
      "time": "",
      "room": "Closing",
      "level": "",
      "group": [],
      "groupTitle": "Closing",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Nicola Bosco",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "3655670483b76497c0def0587096e40d",
      "itemType": "type2",
      "artistName": "Andrea Stern",
      "sessionMainTitle": "Moment of gratitude for this beautiful day for everyone here",
      "time": "",
      "room": "Closing",
      "level": "",
      "group": [],
      "groupTitle": "Closing",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Andrea Stern",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    },
    {
      "id": "b8a0d0599f5e173c3f2267a3a8cad258",
      "itemType": "type2",
      "artistName": "Marc Morozumi",
      "sessionMainTitle": "Taking this with you, into your everyday life",
      "time": "",
      "room": "Closing",
      "level": "",
      "group": [],
      "groupTitle": "Closing",
      "groupSubtitle": "",
      "shortMainTitle": "",
      "dateString": "Sat, September 21, 2024",
      "startTime": "",
      "endTime": "",
      "place": "",
      "sessionSubtitle": "",
      "sessionDescription": "",
      "artistOne": "Marc Morozumi",
      "artistTwo": "",
      "artistLocation": "",
      "flag": false,
      "flagIncludeInNow": false
    }
  ],
  "dataSpecialSessions": {},
  "dataStyles": {},
  "dataLocation": {},
  "dataModelProgram": []
}