export const modelInitStaticOverwrite =
{

  modelRemoteGetModelUrl: 'https://wqmw4icfr0.execute-api.eu-central-1.amazonaws.com/default/fiestaEleganteModelContent',
  modelRemoteVersionCheckUrl: 'https://wqmw4icfr0.execute-api.eu-central-1.amazonaws.com/default/fiestaEleganteModelVersion',
  modelRemoteUpdateInterval: 55000,

  happeningNowUpdateInterval: 10000,

  festivalName: "Fiesta Elegante",

  modelVersion: 2000,
  dataArtists : {
      'Yoyo Flow': { fullName: `Yoyo Flow`, insta: ``, bio: `was born, grew up and graduated choreographic education in Cuba. Gorgeous, charismatic dancer with a unique Cuban style and energy. Studied in various courses of the famous school of Tony Mendez (Havana, Cuba). Yoandi has experience performing in theaters`, facebook: ``, portrait: `yoyo_flow.png` },
      'Yenifer Lavin': { fullName: `Yenifer Lavin`, insta: ``, bio: `She comes from Cuba, where she went to the National School of Art in Havana. There, she studied modern styles of dance as well as traditional Cuban dance. Now, she lives in Barcelona, where she is involved in the global dance community. She doesn’t just dance; she also creates dance routines and teaches others. \n She has been a part of many important dance events and shows in Spain, working with well-known people like singer Dua Lipa and popular brands like Nike. Presently, she dances alongside Yoandy Villaurrutia, who is also a talented dancer and creator of dance routines. Together, they create beautiful and impressive dance performances.`, facebook: ``, portrait: `yenifer_lavin.png` },
      'Eloy J Rojas': { fullName: `Eloy J Rojas`, insta: ``, bio: `Is a renowned dancer and choreographer specializing in Latin and Afro-Cuban rhythms. Trained in Venezuela and Mexico, he founded EJR Studio in Berlin and gained fame for his innovative techniques. Eloy is a multiple award-winner, including top prizes in Amsterdam and Berlin. His groundbreaking 2022 project, \"From the Roots,\" earned federal funding and set a new standard for Latin dance in Europe. Today, he continues to captivate audiences and students globally.`, facebook: ``, portrait: `eloy_j_rojas.png` },
      'Roger Palombella': { fullName: `Roger Palombella`, insta: `roger_palombella_dancer`, bio: `Is an Italian salsa dancer, animator, and instructor from southern Italy, Barletta. He studied with the best Italian and Cuban trainers, he also developed his skills in Cuban Timba where he mixes salsa steps with Afro technique, interesting musicality and bodymovment, playing with dynamics and good flow!`, facebook: ``, portrait: `roger_palombella.png` },
      'Edyta Kwasna': { fullName: `Edyta Kwasna`, insta: ``, bio: `Has the highest international S class in ballroom dancing. She has participated in numerous national and international tournaments. She represented Poland, Spain and the USA. Her desire to travel and explore the world is so big that she decided to combine it with dance. She had the opportunity to share her dance skills in Singapore, New York and Barcelona, where she lived in each of these places. She perfected her skills in Cuba, which will forever remain in her heart, thats why the last years she focused so much on Cuban culture.`, facebook: ``, portrait: `edyta_kwasna.png` },
      'Yuliet Estrada': { fullName: `Yuliet Estrada`, insta: ``, bio: `Yuliet, born in Havana, has been devoted to dance from a young age. She blossomed as a dancer at the Conjunto Folclorico de la Universidad de la Habana, learning various dance forms and techniques. Her talent shone bright when she won first place at the 1st International Festival of Popular and Ballroom Dances in Havana in 2007. \n Yuliet has performed in numerous shows and competitions, absorbing knowledge and style from various accomplished dancers and institutions. A significant part of her journey was spent at Laura Alonso's Prodanza Academy of Dance, where she embraced diverse dance fusion styles. \n In 2008, Yuliet moved to Oslo, Norway, where she evolved as a dancer and choreographer, contributing to significant projects and dance schools like SalsaKompaniet. Here, she collaborates with Andy Varona, and together they launched the Bailan2 Project, gaining substantial recognition. \n Specializing in dances like salsa, reggaeton, son, rumba, and Afro-Cuban, her journey, marked by significant achievements and collaborations, speaks volumes of her dedication and mastery in dance.`, facebook: ``, portrait: `yuliet_estrada.png` },
      'Andy Varona': { fullName: `Andy Varona`, insta: ``, bio: `Born in Havana, Cuba, he was drawn to music and dance from a tender age, finding his rhythm in urban genres like reggaeton. His professional journey blossomed in 2007 with Cuba’s prestigious Narciso Medina modern dance company. A significant chapter of his journey was enriched by experiences with eminent folkloric groups such as Raíces Profundas and the Conjunto Folclórico Nacional de Cuba. \n In 2014, accolades graced him as he was titled the 'First Dancer' by the National Council of Performing Arts of Cuba and became part of the distinguished rumba group, Osain del Monte. His artistry also illuminated the stages of the Buena Vista Social Club show. \n Europe welcomed his talent in 2014, where his presence resonated in the international festival scenes, marking him as a prominent young male figure in dance. Now residing in Norway, he collaborates with his partner, Yuliet Estrada, on the project Bailan2, and contributes his expertise to Salsakompaniet, one of Norway’s leading dance schools.`, facebook: ``, portrait: `andy_varona.png` },
      'Laura Del Vecchio': { fullName: `Laura Del Vecchio`, insta: ``, bio: `Is more than just a dancer; she's a dance virtuoso with a career spanning from hip-hop to Salsa Cubana. Starting at age 6, Laura has dazzled audiences alongside stars like the Spice Girls and Thomas Gottschalk. She's won German dance championships. \n Laura brings a fusion of Salsa, Hip-Hop, Afro, Reggaeton, and Bachata to stages worldwide. \n She was on the big screen in \"Willkommen bei den Hartmanns\" and also as a choreographer for Let's Dance and fashion shows.`, facebook: ``, portrait: `laura_del_vecchio.png` },
      'Timo Lingnau': { fullName: `Timo Lingnau`, insta: `timo_lingnau`, bio: `Timo is a dancer, choreographer, dance teacher, and DJ. His dance career began in his hometown of Augsburg under the tutelage of Emilito Herrera. While teaching at Herrera's dance school, Timo was also a part of the successful show team of Cuban Salsa Power. With this team, he won the German Championship for Rueda de Casino in 2013. \n He has also showcased his talent in group and duo performances at salsa congresses and concerts both domestically and internationally. In 2018, he clinched the first place with Julia von Oy at the \"Timba Competition\" during the prestigious Festival Internacional de Guaguancó Afro-Cubano in Lloret de Mar, Spain. 'La Maña' was the first show Timo choreographed for a group, premiering in Hamburg in 2022, followed by further performances in Berlin.\n Since 2014, Timo has been living in Berlin. There, he founded the dance school Cuban Salsa Power Berlin, which has since grown into the largest school for Cuban dances in the capital.\n Known as DJ TiMueve, Timo is a sought-after figure not just in Berlin. He is appreciated for his skillful blend of modern and classic tracks and Son Cubano.`, facebook: ``, portrait: `timo_lingnau.png` },
      'Lucas Flemming': { fullName: `Lucas Flemming`, insta: ``, bio: `Lucas' journey as a dancer and dance instructor began as a classical music student at the prestigious HfM \"Hanns Eisler\" in Berlin. During his studies, he discovered his passion for dancing and enjoyed his training as a dancer and dance teacher at the Cuban Salsa Power Berlin dance school, where he soon began teaching. \n Lucas' expertise extends from dance methodology and deepening musicality in dance to the continuous development of innovative concepts in teaching dance styles such as Salsa Cubana, Son Cubano, and Rumba Cubana. His passion for teaching led him to work with renowned artists and teachers like Danger Rodriguez, Yunaisy Farray, Leivan García, and Fredy García Batista, where he expanded his repertoire. Moreover, Lucas is a proud co-founder and co-host of the scientific podcast on Cuban music titled \"Tanzpause,\" where the cultural and musical depths of the fascinating Cuban music and dance culture are explored.`, facebook: ``, portrait: `lucas_flemming.png` },
      'Kimberly Wirt': { fullName: `Kimberly Wirt`, insta: ``, bio: `Kimberly's journey into the world of dance commenced in her early years, evolving significantly within the realms of Modern and Contemporary Dance. As a member of a Berlin dance formation, she competed in tournaments across Germany, notably competing in the 2nd national league of JMC Germany North/East/West in both 2016 and 2017. The technical prowess honed during this period, encompassing the foundations of ballet and contemporary dance, now serve as an invaluable wellspring of knowledge in her capacity as a dance teacher. \n Since venturing into the captivating universe of Cuban salsa and related dance forms, Kimberly has been an active participant in numerous festivals and private sessions. Shaped by influential figures within the global Salsa Cubana scene, she now has become one of the most transformative and influential teachers in the Berlins Cuban Salsa scene. Kimberly brings to the stage six years of teaching expertise alongside her esteemed dance partner, Lucas Flemming, with whom she continues to consistently evolve. \n Through dance, she not only aims to enthuse her students about the profound world of Salsa Cubana and related dances but also strives to unite people in the joy of movement and music." }`, facebook: ``, portrait: `kimberly_wirt.png` },
  },

  dataScheduleRaw:
      [
          { id: 1201, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Oliwia', sessionMainTitle: 'Funky Salsa - Solo', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Elegant Hall`, level: `1`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexandra Toledo', artistTwo: '', flag: false },
          { id: 1202, group: [1201, 1202, 1203, 1204, 1205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Helen & Yago', sessionMainTitle: 'Conexion', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '11:00 - 12:00', room: `Dark Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },

          { id: 1301, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Osmani', sessionMainTitle: 'Timba Fusion', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Elegant Hall`, level: `2`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: false },
          { id: 1302, group: [1301, 1302, 1303, 1304, 1305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Yosniel', sessionMainTitle: 'Salsa Musicality', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '12:15 - 13:15', room: `Dark Room`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Lynet Rubio', flag: true },

          { id: 1103, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Break', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '13:15 - 14:15', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T13:15', endTime: '2024-06-14T14:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

          { id: 1401, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jose', sessionMainTitle: 'Salsa Con Afro & Rumba', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Elegant Hall`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Kimberly Wirt', flag: false },
          { id: 1402, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Oliwia', sessionMainTitle: 'Lady Styling', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Dark Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Angela Jauregui', artistTwo: '', flag: true },
          { id: 1403, group: [1401, 1402, 1403, 1404, 1405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '14:15 - 15:15', room: `Bootcamp Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },

          { id: 1501, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lucas & Kimmy', sessionMainTitle: 'Casino Transiciones', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Elegant Hall`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lucas Flemming', artistTwo: 'Kimberly Wirt', flag: false },
          { id: 1502, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio', sessionMainTitle: 'Rumba Columbia', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Dark Room`, level: `1`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: '', flag: true },
          { id: 1503, group: [1501, 1502, 1503, 1504, 1505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Lynet', sessionMainTitle: 'Afro-Conte﻿mporary', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '15:30 - 16:30', room: `Bootcamp Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Lynet Rubio', artistTwo: '', flag: true },

          { id: 1601, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Elegant Hall`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
          { id: 1602, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Wendy', sessionMainTitle: 'Reggaeton ', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Dark Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Wendy Solanch', artistTwo: '', flag: true },
          { id: 1603, group: [1601, 1602, 1603, 1604, 1605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jonas (Tanzpause)', sessionMainTitle: 'An interactive Journey: Roots of Timba', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '16:45 - 17:45', room: `Bootcamp Room`, level: ``, partnerWork: ``, levelSpecial: `3`, startTime: '2024-07-20T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Jonas Reichert', artistTwo: '', flag: true },

          { id: 1700, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Sat, July 20th 2024', time: '', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

          { id: 2201, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Alex Toledo', sessionMainTitle: 'Son Cubano', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Elegant Hall`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Alexandra Toledo', flag: false },
          { id: 2202, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido', sessionMainTitle: 'Pasos con estilo', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Dark Room`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: '', flag: true },
          { id: 2203, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Cha Cha Cha Partnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Bootcamp Room`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
          { id: 2204, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'VODOO', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Viñales`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
          { id: 2205, group: [2201, 2202, 2203, 2204, 2205], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Técnica', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '11:00 - 12:00', room: `Trinidad`, level: `0`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T11:00', endTime: '2024-06-14T12:00', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

          { id: 2301, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Timba PArtnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Elegant Hall`, level: `2`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
          { id: 2302, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'FOOTWORK LOCO', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Dark Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
          { id: 2303, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Bolero Partnerwork', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Bootcamp Room`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
          { id: 2304, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'GÜiR﻿O', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Viñales`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
          { id: 2305, group: [2301, 2302, 2303, 2304, 2305], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda UNusual Trans﻿icions', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '12:15 - 13:15', room: `Trinidad`, level: `0`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T12:15', endTime: '2024-06-14T13:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

          { id: 2103, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type3', flagIncludeInNow: false, artistName: '', sessionMainTitle: 'Lunch Break', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '13:15 - 14:15', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T13:15', endTime: '2024-06-14T14:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },

          { id: 2401, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Ido & Wendy', sessionMainTitle: 'CASINO PARTNERWORK ', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Elegant Hall`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ido Flaishon', artistTwo: 'Wendy Solanch', flag: false },
          { id: 2402, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger & Kimmy', sessionMainTitle: 'CASINO CON RUMBA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Dark Room`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: 'Kimberly Wirt', flag: true },
          { id: 2403, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo & Lynet', sessionMainTitle: 'Danzón', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Bootcamp Room`, level: `0`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: 'Lynet Rubio', flag: true },
          { id: 2404, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Angela', sessionMainTitle: 'MAKUTA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Viñales`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Angela Jauregui', artistTwo: '', flag: true },
          { id: 2405, group: [2401, 2402, 2403, 2404, 2405], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Helen & Tanja', sessionMainTitle: 'SON RUEDA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '14:15 - 15:15', room: `Trinidad`, level: `1`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T14:15', endTime: '2024-06-14T15:15', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Helen', artistTwo: 'Tanja', flag: true },

          { id: 2501, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Silvio & Angela', sessionMainTitle: 'Son Planchas &  Tornillos', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Elegant Hall`, level: `1`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Silvio Perez', artistTwo: 'Angela Jauregui', flag: false },
          { id: 2502, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo & Wendy', sessionMainTitle: 'CASINO NUDOS', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Dark Room`, level: `2`, partnerWork: `1`, levelSpecial: ``, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Wendy Solanch', flag: true },
          { id: 2503, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Jonas (Tanzpause)', sessionMainTitle: 'Structure of Timba', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Bootcamp Room`, level: ``, partnerWork: ``, levelSpecial: `3`, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Jonas Reichert', artistTwo: '', flag: true },
          { id: 2504, group: [2501, 2502, 2503, 2504, 2505], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Leonardo', sessionMainTitle: 'Chachalokafun', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '15:30 - 16:30', room: `Viñales`, level: `1`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T15:30', endTime: '2024-06-14T16:30', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Leonardo Moya', artistTwo: '', flag: true },

          { id: 2601, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: 'Browse Rooms:', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alex Toledo', sessionMainTitle: 'Ladystyling', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Elegant Hall`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexandra Toledo', artistTwo: '', flag: false },
          { id: 2602, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Roger', sessionMainTitle: 'MEN STYLE ', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Dark Room`, level: `0`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Ruggiero Palombella', artistTwo: '', flag: true },
          { id: 2603, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Timo & Lucas', sessionMainTitle: 'Timba Musicality', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Bootcamp Room`, level: `2`, partnerWork: ``, levelSpecial: ``, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Timo Lingnau', artistTwo: 'Lucas Flemming', flag: true },
          { id: 2604, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Alexander Carbó', sessionMainTitle: 'IYESA', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Viñales`, level: `0`, partnerWork: ``, levelSpecial: `1`, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Alexander Carbo', artistTwo: '', flag: true },
          { id: 2605, group: [2601, 2602, 2603, 2604, 2605], groupTitle: '', groupSubtitle: '', itemType: 'type1', flagIncludeInNow: false, artistName: 'Sassan', sessionMainTitle: 'Rueda Llanta', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '16:45 - 17:45', room: `Trinidad`, level: `2`, partnerWork: ``, levelSpecial: `2`, startTime: '2024-07-21T16:45', endTime: '2024-06-14T17:45', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: 'Sassan Alivaliollahi', artistTwo: '', flag: true },

          { id: 2700, group: [], groupTitle: '', groupSubtitle: '', itemType: 'type5', flagIncludeInNow: false, artistName: '', sessionMainTitle: '', shortMainTitle: '', dateString: 'Sun, July 20th 2024', time: '', room: ``, level: ``, partnerWork: ``, levelSpecial: ``, startTime: '', endTime: '', floor: '', sessionSubtitle: '', sessionDescription: '', artistOne: '', artistTwo: '', flag: false },
      ],

      "dataSpecialSessions": {
        "Absolute Beginner Track - Salsa": {
          "company": "Somos Dance Studio",
          "description": "Discover the joy of dance at the CALDAC convention with our Absolute Beginner Track workshops! Perfect for those new to Salsa or Bachata, these workshops are designed to welcome you into the world of dance with no prior experience required. Separate classes for Salsa and Bachata ensure that you get the focused attention you need to start your dance journey. Best of all, these workshops are free with the purchase of a full pass or VIP pass—just be sure to sign up in advance to secure your spot. It’s all about fun, no judgments, and a fantastic way to get involved in the weekend’s festivities. Come join us and take your first steps in dance!",
          "title": "Absolute Beginner Track - Salsa",
          "price": "0",
          "signup": "no",
          "artistNames": [
            "Sisy Ayala"
          ]
        },
        "Absolute Beginner Track - Bachata": {
          "company": "Somos Dance Studio",
          "description": "Discover the joy of dance at the CALDAC convention with our Absolute Beginner Track workshops! Perfect for those new to Salsa or Bachata, these workshops are designed to welcome you into the world of dance with no prior experience required. Separate classes for Salsa and Bachata ensure that you get the focused attention you need to start your dance journey. Best of all, these workshops are free with the purchase of a full pass or VIP pass—just be sure to sign up in advance to secure your spot. It’s all about fun, no judgments, and a fantastic way to get involved in the weekend’s festivities. Come join us and take your first steps in dance!",
          "title": "Absolute Beginner Track - Bachata",
          "price": "0",
          "signup": "no",
          "artistNames": [
            "Jared and Nicole"
          ]
        },
        "AnD Bachata Instructor - Certification Training": {
          "company": "AnD Academic Network of Dance",
          "description": "- Open to intermediate-advanced dancers\n- Open to (but not limited to) instructors\n- End-of-Course assessment for certification is optional\n\nThis certification course is designed with the ultimate goal of helping the intermediate-advanced dancers and instructors with delivering quality instruction to their students on the AnD Bachata style and technique. \n\nComprised of 4 Modules:\n1. Bachata History & Evolution (Dance and Musical Instrumentation)\n2. Detailed AnD Technique and Fundamental Basic Movements\n3. Partnering Principles to Lead and Follow the Basics\n4. Recommendations and Best Practices for Instructors\n\nCourse Length: approx ~5-6 hours\n\n** To successfully complete the course and receive your official AnD Certificate of Completion you will need to follow instructions provided to coordinate your end of course assessment. PLEASE NOTE certificate is not automatically issued. We reserve the right to deny a certificate of completion if you are not able to successfully demonstrate sufficient understanding of the content. You are generally only allowed to schedule the assessment once.",
          "title": "AnD Bachata Instructor - Certification Training",
          "price": "200",
          "signup": "yes",
          "artistNames": [
            "Alex and Desiree"
          ]
        },
        "Heels Challenge": {
          "company": "Creations by Rafa",
          "description": "Join us at the CALDAC convention for the Rafa Heels Bootcamp, a unique experience designed to boost your self-confidence and help you feel great in your own skin! Whether you're a seasoned dancer or a complete beginner, no prior experience is necessary, and wearing heels is entirely optional. From Friday, October 18th, to Sunday, October 20th, 2024, you'll work closely with Rafa, refining your skills and building your confidence. As a special highlight, participants have the option to perform with Rafa on Sunday night—though it's entirely up to you! Please note that this bootcamp requires a separate purchase in addition to your full or VIP pass. Don't miss this chance to elevate your dance journey!",
          "title": "Heels Challenge",
          "price": "50",
          "signup": "yes",
          "artistNames": [
            "Rafa Gonzalez"
          ]
        }
      },

  dataStyles : {
      'type1': { note: 'workshops', color1: '#312816', color2: '#312816', color3: '#f8f6d3', bgColor: '#bfa269' },
      'type2': { note: 'city', color1: '#f8f6d3', color2: '#312816', color3: '#FFFFFF', bgColor: '#d7c8ac' },
      'type3': { note: 'bootcamp', color1: '#312816', color2: '#f8f6d3', color3: '#010101', bgColor: '#fefac9' },
      'type4': { note: 'party', color1: '#f8f6d3', color2: '#f2aa3e', color3: '#FFFFFF', bgColor: '#3e3b3a' },
  },

  dataLocation : {
      'altemuenze': { locationName: `Alte Münze`, mapObj: { lat: '52.5161353', lon: '13.4065007', q: `Alte+Münze` } },
      'bebop': { locationName: `Bebop`, mapObj: { lat: '52.5026902', lon: '13.4382444', q: `Bebop` } },
      'belushis': { locationName: `Belushi's Mitte`, mapObj: { lat: '52.5236727', lon: '13.3883634', q: `Belushi's+Berlin+(Mitte)` } },
      'berlindanceinstitute': { locationName: `Berlin Dance Institute`, mapObj: { lat: '52.463359', lon: '13.3656772', q: `Berlin+Dance+Institute` } },
      'soda': { locationName: `Soda Club`, mapObj: { lat: '52.5394092', lon: '13.4117562', q: `Soda+Club+Berlin` } },
      'citytour': { locationName: `Pariser Platz / Brandenburger Tor`, mapObj: { lat: '52.5157516', lon: '13.3769428', q: `Academy+of+Arts` } },
  },

  dataModelProgram: [
      { id: 2, type: 'type4', title: 'PREPARTY', dateText: "Thu, 18.07.24", timeText: "20:15 - 01:00", location: 'soda', locationAdress: 'Schönhauser Allee 36, 10435 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-18T20:15:00.000', endTime: '2024-07-19T01:00:00.000', description: "Join us for a social dance extravaganza across 5 dancefloors featuring Salsa Cubana, Mambo, Bachata, Zouk, and Kizomba." },
      { id: 3, type: 'type2', title: 'CITY TOUR', dateText: "Fri, 19.07.24", timeText: "13:15 - 15:30", location: 'citytour', locationAdress: 'Pariser Platz 4, 10117 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-19T13:15:00.000', endTime: '2024-07-19T15:30:00.000', description: "Two-hour city tour through Berlin's historic city center. Dance some Ruedas at iconic landmarks and immerse yourself in the city's rich history and culture." },
      { id: 4, type: 'type4', title: 'ROOFTOP SOCIAL', dateText: "Fri, 19.07.24", timeText: "15:30 - 20:00", location: `belushis`, locationAdress: 'Ziegelstraße 28, 10117 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-19T15:30:00.000', endTime: '2024-07-19T20:00:00.000', description: "Lively Dance-Social on a breathtaking rooftop in the city center. Enjoy the spectacular summer evening sky, savor ice-cold drinks and dance the afternoon away." },
      { id: 5, type: 'type3', title: 'Beginner Bootcamp', dateText: "Fri, 19.07.24", timeText: "18:00 - 20:30", location: 'bebop', locationAdress: 'Pfuelstraße 5, 10997 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-19T18:00:00.000', endTime: '2024-07-19T20:30:00.000', description: "Get ready for an intensive dive into Salsa Cubana, tailored to beginners with some experience! Our instructors, Timo & Giulia, will show you how to combine simple elements into fun and impressive figures." },
      { id: 6, type: 'type4', title: 'Welcome Party', dateText: "Fri, 19.07.24", timeText: "21:00 - 03:00", location: 'bebop', locationAdress: 'Pfuelstraße 5, 10997 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-19T21:00:00.000', endTime: '2024-07-20T03:00:00.000', description: "Official Festival Party\n  21:00 - 22:00: Preparty Workshop\n  22:00 - 03:00: Party" },
      { id: 7, type: 'type1', title: 'Workshops', dateText: "Sat, 20.07.24", timeText: "11:00 - 18:00", location: 'berlindanceinstitute', locationAdress: 'Egelingzeile 6, 12103 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-20T11:00:00.000', endTime: '2024-07-20T18:00:00.000', description: "Go to the workshop planner to mark your favorite sessions." },
      { id: 8, type: 'type4', title: 'Gala Party', dateText: "Sat, 20.07.24", timeText: "21:00 - 04:00", location: 'altemuenze', locationAdress: 'Molkenmarkt 2, 10179 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-20T21:00:00.000', endTime: '2024-07-21T04:00:00.000', description: "21:00 - 22:00: Preparty Workshop\n 22:00 - 04:00: Gala Party\n 23:00: Orishas Show & Rumba Abierta" },
      { id: 9, type: 'type1', title: 'Workshops', dateText: "Sun, 21.07.24", timeText: "11:00 - 18:00", location: 'berlindanceinstitute', locationAdress: 'Egelingzeile 6, 12103 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-21T11:00:00.000', endTime: '2024-07-21T18:00:00.000', description: "Go to the workshop planner to mark your favorite sessions." },
      { id: 10, type: 'type4', title: 'Goodbye Party', dateText: "Sun, 21.07.24", timeText: "20:15 - 01:00", location: 'soda', locationAdress: 'Schönhauser Allee 36, 10435 Berlin', tickets: ['Berlin Experience Ticket', "All-Inclusive Pass,"], startTime: '2024-07-21T20:15:00.000', endTime: '2024-07-22T01:00:00.000', description: "Special:  23:00: Show" },
      { id: 11, type: 'type5', title: 'EMPTY', dateText: "", timeText: "", location: '', locationAdress: '', tickets: [], startTime: '', endTime: '', description: "" },
      { id: 12, type: 'type5', title: 'EMPTY', dateText: "", timeText: "", location: '', locationAdress: '', tickets: [], startTime: '', endTime: '', description: "" },
  ],

  dataTicketSales : {
      earlyBirdStartTimeString: '2024-07-21T05:00:00.000'
  }
}
